pipeline {
    agent any

    environment {
        SCANNER_HOME = tool 'sonar-scanner'
        MAVEN_HOME = tool 'maven3'
        PATH = "${MAVEN_HOME}/bin:${env.PATH}"
        IMAGETAG = "build-${env.BUILD_NUMBER}"  // ⬅ Tag dynamique
    }

    parameters {
        password(name: 'PASSWD', defaultValue: '', description: 'Mot de passe ou token GitHub pour le pipeline CD')
    }

    stages {

        stage("Clean Workspace") {
            steps {
                cleanWs()
            }
        }

        stage("Git Checkout") {
            steps {
                git branch: 'master', url: 'https://github.com/Paradox2001/Api-sinistre.git'
            }
        }

        stage("Tests Unitaires") {
            steps {
                dir('api-sinistre') {
                    sh 'mvn test'
                }
            }
        }

        stage("Génération du rapport de couverture") {
            steps {
                dir('api-sinistre') {
                    sh 'mvn jacoco:report'
                }
            }
        }

          stage("OWASP Dependency Check") {
            steps {
                dependencyCheck additionalArguments: '--scan ./ --disableYarnAudit --disableNodeAudit', odcInstallation: 'DP-Check'
                dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
            }
        }

        stage("Analyse SonarQube") {
            steps {
                withSonarQubeEnv('sonar-server') {
                    dir('api-sinistre') {
                        sh """
                        mvn clean verify sonar:sonar \
                        -Dsonar.projectKey=axa_sinistre \
                        -Dsonar.projectName=axa_sinistre \
                        -Dsonar.sources=src/main/java \
                        -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
                        """
                    }
                }
            }
        }

        stage("Vérification Quality Gate") {
            steps {
                script {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

      
        stage("Build Docker Image") {
            steps {
                sh "docker build -t zakariahmimssa/axa_sinistre:${IMAGETAG} ./api-sinistre"
            }
        } 
        stage("Push vers DockerHub") {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'dockercred') {
                        sh "docker push zakariahmimssa/axa_sinistre:${IMAGETAG}"
                    }
                }
            }
        }


          stage("Scan Trivy") {
    steps {
        sh "trivy image zakariahmimssa/axa_sinistre:${IMAGETAG} > trivy.txt"
    }
}

        stage("Docker Scout Scan") {
            steps {
                withCredentials([usernamePassword(credentialsId: 'scout-token', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin'
                    sh "docker-scout quickview zakariahmimssa/axa_sinistre:${IMAGETAG}"
                    sh "docker-scout cves zakariahmimssa/axa_sinistre:${IMAGETAG}"
                    sh "docker-scout recommendations zakariahmimssa/axa_sinistre:${IMAGETAG}"
                }
            }
        }

        stage('Smoke Test') {
    steps {
        echo "Smoke Test the Docker image"
         // Supprimer le conteneur s'il existe déjà
        sh "docker rm -f smokerun || true"
        sh "docker run -d --name smokerun -p 8082:8080 zakariahmimssa/axa_sinistre:${IMAGETAG}"
        sh "sleep 60; curl -f http://localhost:8082/api/sinistres || (echo 'Health check failed'; exit 1)"
        sh "docker rm --force smokerun"
    }
}


        stage("Déclenchement du Pipeline CD") {
            steps {
                build job: 'app-cd', // ⬅️ Nom exact de ton job CD Jenkins
                parameters: [
                    string(name: 'IMAGETAG', value: "${IMAGETAG}"),
                    password(name: 'PASSWD', value: params.PASSWD),
                    //choice(name: 'environment', value: 'release')
                ]
            }
        }
    }

    post {
        always {
            emailext attachLog: true,
                subject: "'${currentBuild.result}' - Build ${env.BUILD_NUMBER}",
                body: """
                    <html>
                    <body>
                        <h3 style="color: #007ACC;">Pipeline CI terminé</h3>
                        <ul>
                            <li><b>Projet :</b> ${env.JOB_NAME}</li>
                            <li><b>Build # :</b> ${env.BUILD_NUMBER}</li>
                            <li><b>Tag image :</b> ${IMAGETAG}</li>
                            <li><b>URL :</b> <a href="${env.BUILD_URL}">${env.BUILD_URL}</a></li>
                        </ul>
                        <p>Voir le fichier Trivy joint pour les vulnérabilités.</p>
                    </body>
                    </html>
                """,
                to: 'hmimssazakaria@gmail.com',
                mimeType: 'text/html',
                attachmentsPattern: 'trivy.txt'
        }
    }
}
